/*
 * This file is generated by jOOQ.
 */
package io.skai.reservation.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ticket implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long passengerId;
    private Long flightId;
    private BigDecimal price;
    private String seatNumber;

    public Ticket() {}

    public Ticket(Ticket value) {
        this.id = value.id;
        this.passengerId = value.passengerId;
        this.flightId = value.flightId;
        this.price = value.price;
        this.seatNumber = value.seatNumber;
    }

    public Ticket(
        Long id,
        Long passengerId,
        Long flightId,
        BigDecimal price,
        String seatNumber
    ) {
        this.id = id;
        this.passengerId = passengerId;
        this.flightId = flightId;
        this.price = price;
        this.seatNumber = seatNumber;
    }

    /**
     * Getter for <code>airlines-db.ticket.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>airlines-db.ticket.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>airlines-db.ticket.passenger_id</code>.
     */
    public Long getPassengerId() {
        return this.passengerId;
    }

    /**
     * Setter for <code>airlines-db.ticket.passenger_id</code>.
     */
    public void setPassengerId(Long passengerId) {
        this.passengerId = passengerId;
    }

    /**
     * Getter for <code>airlines-db.ticket.flight_id</code>.
     */
    public Long getFlightId() {
        return this.flightId;
    }

    /**
     * Setter for <code>airlines-db.ticket.flight_id</code>.
     */
    public void setFlightId(Long flightId) {
        this.flightId = flightId;
    }

    /**
     * Getter for <code>airlines-db.ticket.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>airlines-db.ticket.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>airlines-db.ticket.seat_number</code>.
     */
    public String getSeatNumber() {
        return this.seatNumber;
    }

    /**
     * Setter for <code>airlines-db.ticket.seat_number</code>.
     */
    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Ticket other = (Ticket) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.passengerId == null) {
            if (other.passengerId != null)
                return false;
        }
        else if (!this.passengerId.equals(other.passengerId))
            return false;
        if (this.flightId == null) {
            if (other.flightId != null)
                return false;
        }
        else if (!this.flightId.equals(other.flightId))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.seatNumber == null) {
            if (other.seatNumber != null)
                return false;
        }
        else if (!this.seatNumber.equals(other.seatNumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.passengerId == null) ? 0 : this.passengerId.hashCode());
        result = prime * result + ((this.flightId == null) ? 0 : this.flightId.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.seatNumber == null) ? 0 : this.seatNumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ticket (");

        sb.append(id);
        sb.append(", ").append(passengerId);
        sb.append(", ").append(flightId);
        sb.append(", ").append(price);
        sb.append(", ").append(seatNumber);

        sb.append(")");
        return sb.toString();
    }
}
