version: "3.3"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: airlines-db
      MYSQL_USER: vadim
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  mysql-db-test:
    image: mysql:latest
    container_name: mysql-testdb
    environment:
      MYSQL_DATABASE: airlines-db
      MYSQL_USER: sa
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3307:3306"

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - REDIS_APPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  my-db:
  redis-data:
