version: "3.3"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ticket
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

#  redis:
#    container_name: "redis"
#    image: 'redis:alpine'
#    command: redis-server --requirepass ${REDIS_PASS:-password123}
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#      - redis-conf:/usr/local/etc/redis/redis.conf
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      -

volumes:
  my-db:
#  redis-data:
#  redis-conf:
