/*
 * This file is generated by jOOQ.
 */
package io.skai.reservation.jooq.tables;


import io.skai.reservation.jooq.AirlinesDb;
import io.skai.reservation.jooq.Keys;
import io.skai.reservation.jooq.tables.records.AirportRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Airport extends TableImpl<AirportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>airlines-db.airport</code>
     */
    public static final Airport AIRPORT = new Airport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AirportRecord> getRecordType() {
        return AirportRecord.class;
    }

    /**
     * The column <code>airlines-db.airport.id</code>.
     */
    public final TableField<AirportRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>airlines-db.airport.name</code>.
     */
    public final TableField<AirportRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>airlines-db.airport.country_code</code>.
     */
    public final TableField<AirportRecord, String> COUNTRY_CODE = createField(DSL.name("country_code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>airlines-db.airport.city</code>.
     */
    public final TableField<AirportRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Airport(Name alias, Table<AirportRecord> aliased) {
        this(alias, aliased, null);
    }

    private Airport(Name alias, Table<AirportRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>airlines-db.airport</code> table reference
     */
    public Airport(String alias) {
        this(DSL.name(alias), AIRPORT);
    }

    /**
     * Create an aliased <code>airlines-db.airport</code> table reference
     */
    public Airport(Name alias) {
        this(alias, AIRPORT);
    }

    /**
     * Create a <code>airlines-db.airport</code> table reference
     */
    public Airport() {
        this(DSL.name("airport"), null);
    }

    public <O extends Record> Airport(Table<O> child, ForeignKey<O, AirportRecord> key) {
        super(child, key, AIRPORT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AirlinesDb.AIRLINES_DB;
    }

    @Override
    public Identity<AirportRecord, Long> getIdentity() {
        return (Identity<AirportRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AirportRecord> getPrimaryKey() {
        return Keys.KEY_AIRPORT_PRIMARY;
    }

    @Override
    public List<UniqueKey<AirportRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AIRPORT_NAME);
    }

    @Override
    public Airport as(String alias) {
        return new Airport(DSL.name(alias), this);
    }

    @Override
    public Airport as(Name alias) {
        return new Airport(alias, this);
    }

    @Override
    public Airport as(Table<?> alias) {
        return new Airport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Airport rename(String name) {
        return new Airport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Airport rename(Name name) {
        return new Airport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Airport rename(Table<?> name) {
        return new Airport(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
