/*
 * This file is generated by jOOQ.
 */
package io.skai.reservation.jooq;


import io.skai.reservation.jooq.tables.Airport;
import io.skai.reservation.jooq.tables.Flight;
import io.skai.reservation.jooq.tables.HistoryTicket;
import io.skai.reservation.jooq.tables.Passenger;
import io.skai.reservation.jooq.tables.Ticket;


/**
 * Convenience access to all tables in airlines-db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>airlines-db.airport</code>.
     */
    public static final Airport AIRPORT = Airport.AIRPORT;

    /**
     * The table <code>airlines-db.flight</code>.
     */
    public static final Flight FLIGHT = Flight.FLIGHT;

    /**
     * The table <code>airlines-db.history_ticket</code>.
     */
    public static final HistoryTicket HISTORY_TICKET = HistoryTicket.HISTORY_TICKET;

    /**
     * The table <code>airlines-db.passenger</code>.
     */
    public static final Passenger PASSENGER = Passenger.PASSENGER;

    /**
     * The table <code>airlines-db.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;
}
